  - name: install apache on webserver
  hosts: webserver
  tasks:
  - name: install apache2 package
    apt:
     name: apache2
     state: present
    become: yes
  - name: check if service is started
    service:
     name: apache2
     state: started
  - name: install postgresql package
    apt:
     name: php-pgsql
     state: present
    become: yes
